리눅스 환경에서의 빌드를 위한 Makefile 추가 및 README 수정
nuke1115/SortingAlgorithmVisualization pull request #1
Opened 2024-09-22 10:28 UTC by unta1337

* 리눅스 환경에서 빌드할 수 있도록 간단한 Makefile을 추가했습니다.
* 리눅스 환경에서 빌드할 수 있도록 헤더 파일에 쓰인 `\`를 `/`로 대체했습니다.
* README에 프로그램의 스크린샷을 추가했습니다.
* README에 표기된 일부 명령어를 코드 블록으로 감싸도록 했습니다.
* README에서 설명하는 파일에 접근이 용이하도록 파이퍼링크를 추가했습니다.

2024-09-22 10:29 UTC, unta1337 commented
리눅스 환경에서 빌드가 가능함을 확인했지만 혹시 모를 경우를 대비해 윈도우 쪽에서도 여전히 VS를 통한 빌드가 잘 되는지 확인해주시면 좋겠습니다.

감사합니다.

2024-09-23 10:35 UTC, nuke1115 requested changes
Windows의 Visual Studio 환경에서 빌드는 정상적으로 되나, 개행문자(\n)가 정상적으로 작동하지 않는 문제가 있습니다. 해당 부분 수정해주시면 좋겠습니다.
감사합니다.

2024-09-23 11:11 UTC, unta1337 commented
일괄적으로 `\`를 `/`로 바꾸는 과정에서 이스케이핑까지 바꾼 모양입니다. 관련 부분 수정했습니다.

2024-09-23 11:36 UTC, merged

2024-09-23 11:36 UTC, nuke1115 commented
병합 완료했습니다